### ISSUE TITLE
Kanban Review

### ISSUE THREAD

**Issue by rex-9** [rex-9/RubyBank#31]
Link to our project - https://github.com/users/rex-9/projects/3

There are 3 people in this project: @rex-9, @Said-laasri, and @benshidanny11 

@Said-laasri is Team member 1 who is going to handle the Books.
@benshidanny11  is Team member 1 who is going to handle the MusicAlbum.
@rex-9  is Team member 1 who is going to handle the Game.

**Comment by thecodechaser** [comment]
## STATUS: APPROVED 🟢

## Hi @rex-9, @benshidanny11, anmd @Said-laasri👋, 

Your project is complete!  There is nothing else to say other than... it's time to close it :shipit: 
Congratulations! 🎉 

<img src="https://media3.giphy.com/media/g9582DNuQppxC/giphy-downsized-medium.gif"/>

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
